app:
  name: qn-sdk-demo-web

spring:
  profiles:
    active: dev
#    active: pro
#    active: iamlj

win:
  gallery:
    dir: c:/qn-sdk-demo-web/main/
linux:
  gallery:
    dir: /var/local/qn-sdk-demo-web/main/