/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_device_rpc_serialport */

#ifndef _Included_com_device_rpc_serialport
#define _Included_com_device_rpc_serialport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_device_rpc_serialport
 * Method:    getData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_device_rpc_serialport_getData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
